name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build & push container
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/nydata-inc
            --no-stream-logs

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nydata-inc \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nydata-inc \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
